name: Converted Workflow
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-18.04
        python-version: 
          ["3.6", "3.7", "3.8"]

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
    # this Action should follow steps to set up Python build environment
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2  

      - name: "Run tox targets for ${{ matrix.python-version }}"
        run: "python -m tox"
